config/routes.rb
Configstores::Application.routes.draw do
  resources :organizations do
    resources :stores do
      resources :pairs
    end
  end
  
  
  root :to => 'organizations#index'

end

app/models/pair.rb
class Pair < ActiveRecord::Base
  attr_accessible :key, :value

  validates_uniqueness_of :key, :scope => :store_id
  validates :key, :presence => true
  
  belongs_to :store
end

app/controllers/pairs_controller.rb
class PairsController < ApplicationController
  before_filter :load_store

  def load_store
    @store = Store.find(params[:store_id])
  end

  # GET /pairs
  # GET /pairs.json
  def index
    @pairs = @store.pairs

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pairs }
      format.xml { render xml: @pairs }
    end
  end

  # GET /pairs/1
  # GET /pairs/1.json
  def show
    @pair = @store.pairs.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pair }
      format.xml { render xml: @pair }
    end
  end

  # GET /pairs/new
  # GET /pairs/new.json
  def new
    @pair = Pair.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pair }
      format.xml { render xml: @pair }
    end
  end

  # GET /pairs/1/edit
  def edit
    @pair = @store.pairs.find(params[:id])
  end

  # POST /pairs
  # POST /pairs.json
  def create
    @pair = Pair.new(params[:pair])
    @store.pairs << @pair

    respond_to do |format|
      if @store.save
        format.html { redirect_to organization_store_pairs_url(@store.organization, @store), notice: 'Pair was successfully created.' }
        format.json { render json: @pair, status: :created, location: organization_store_pairs_url(@store.organization, @store, @pair) }
        format.xml { render xml: @pair, status: :created, location: organization_store_pairs_url(@store.organization, @store, @pair) }
      else
        format.html { render action: "new" }
        format.json { render json: @pair.errors, status: :unprocessable_entity }
        format.xml { render xml: @pair.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pairs/1
  # PUT /pairs/1.json
  def update
    @pair = @store.pairs.find(params[:id])

    respond_to do |format|
      attrs = params[:pair]
      if @pair.update_attributes({:key => attrs[:key], :value => attrs[:value]})
        format.html { redirect_to organization_store_pairs_url(@store.organization, @store), notice: 'Pair was successfully updated.' }
        format.json { head :no_content }
        format.xml { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pair.errors, status: :unprocessable_entity }
        format.xml { render xml: @pair.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pairs/1
  # DELETE /pairs/1.json
  def destroy
    @pair = @store.pairs.find(params[:id])
    @pair.destroy

    respond_to do |format|
      format.html { redirect_to organization_store_pairs_url(@store.organization, @store) }
      format.json { head :no_content }
      format.xml { head :no_content }
    end
  end
end

app/helpers/pairs_helper.rb
module PairsHelper
end

app/views/pairs/_form.html.haml
= form_for [@store.organization, @store, @pair] do |f|
  -if @pair.errors.any?
    #error_explanation
      %h2= "#{pluralize(@pair.errors.count, "error")} prohibited this pair from being saved:"
      %ul
        - @pair.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :key
    = f.text_field :key, class: 'input'
  .field
    = f.label :value
    = f.text_field :value, class: 'input'
  .actions
    = f.submit 'Save', class: 'btn btn-success'
    = link_to 'Back', organization_store_pairs_path(@store.organization, @store), class: 'btn'

app/views/pairs/edit.html.haml
%h1 Editing pair

= render 'form'

app/views/pairs/index.html.haml
%h1 #{@store.name.capitalize}'s configs

%table.table.table-striped
  %thead
    %tr
      %th Key
      %th Value
      %th
  %tbody
    - @pairs.each do |pair|
      %tr
        %td= pair.key
        %td= pair.value
        %td 
          = link_to 'Show', organization_store_pair_path(@store.organization, @store, pair), class: 'btn'
          = link_to 'Edit', edit_organization_store_pair_path(@store.organization, @store, pair), class: 'btn'
          = link_to 'Destroy', organization_store_pair_path(@store.organization, @store, pair), :confirm => 'Are you sure?', :method => :delete, class: 'btn'

= link_to 'New Pair', new_organization_store_pair_path(@store.organization, @store), class: 'btn'
= link_to 'Back', organization_stores_path(@store.organization), class: 'btn'

app/views/pairs/new.html.haml
%h1 New pair

= render 'form'

app/views/pairs/show.html.haml
%p#notice= notice

%p
  %b Key:
  = @pair.key
%p
  %b Value:
  = @pair.value

= link_to 'Edit', edit_organization_store_pair_path(@store.organization, @store, @pair)
\|
= link_to 'Back', organization_store_pairs_path(@store.organization, @store)