config/routes.rb
Configstores::Application.routes.draw do
  resources :organizations do
    resources :stores do
      resources :pairs
    end
  end
  
  
  root :to => 'organizations#index'

end

app/models/store.rb
class Store < ActiveRecord::Base
  attr_accessible :name

  belongs_to :organization
  has_many :pairs, :dependent => :destroy

  validates :name, :presence => true
  validates_uniqueness_of :name, :scope => :organization_id
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_filter :load_org

  def load_org
    @organization = Organization.find(params[:organization_id])
  end
  # GET /stores
  # GET /stores.json
  def index
    @stores = @organization.stores

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stores }
      format.xml { render xml: @stores }
    end
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @store = @organization.stores.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @store }
      format.xml { render xml: @store }
    end
  end

  # GET /stores/new
  # GET /stores/new.json
  def new
    @store = Store.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @store }
      format.xml { render xml: @store }
    end
  end

  # GET /stores/1/edit
  def edit
    @store = @organization.stores.find(params[:id])
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(params[:store])
    @organization.stores << @store

    respond_to do |format|
      if @organization.save
        format.html { redirect_to organization_stores_path(@organization), notice: 'Store was successfully created.' }
        format.json { render json: @store, status: :created, location: organization_store_url(@organization, @store)}
        format.xml { render xml: @store, status: :created, location: organization_store_url(@organization, @store)}
      else
        format.html { render action: "new" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
        format.xml { render xml: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stores/1
  # PUT /stores/1.json
  def update
    @store = @organization.stores.find(params[:id])

    respond_to do |format|
      attrs = params[:store]
      if @store.update_attributes(:name => attrs[:name])
        format.html { redirect_to organization_stores_path(@organization), notice: 'Store was successfully updated.' }
        format.json { head :no_content }
        format.xml { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
        format.xml { render xml: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store = @organization.stores.find(params[:id])
    @store.destroy

    respond_to do |format|
      format.html { redirect_to organization_stores_url(@organization) }
      format.json { head :no_content }
      format.xml { head :no_content }
    end
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.haml
= form_for([@organization, @store]) do |f|
  -if @store.errors.any?
    #error_explanation
      %h2= "#{pluralize(@store.errors.count, "error")} prohibited this store from being saved:"
      %ul
        - @store.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name, class: 'input'
    = f.text_field :name, class: 'input'
  .actions
    = f.submit 'Save', class: 'btn btn-success'
    = link_to 'Back', organization_stores_path(@organization), class: 'btn'

app/views/stores/edit.html.haml
%h1 Editing store

= render 'form'

app/views/stores/index.html.haml
%h1 #{@organization.name.capitalize}'s stores

%table.table.table-striped
  %thead
    %tr
      %th Name
      %th
  %tbody   
    - @stores.each do |store|
      %tr
        %td= store.name
        %td
          = link_to 'Show configs', organization_store_pairs_path(@organization, store), class: 'btn'
          = link_to 'Edit', edit_organization_store_path(@organization, store), class: 'btn'
          = link_to 'Destroy', organization_store_path(@organization, store), :confirm => 'Are you sure?', :method => :delete, class: 'btn'


= link_to 'New Store', new_organization_store_path(@organization), class: 'btn'
= link_to 'Back', organizations_path, class: 'btn'

app/views/stores/new.html.haml
%h1 New store

= render 'form'

app/views/stores/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @store.name

= link_to 'Pairs', organization_store_pairs_path(@organization, @store) 
\|
= link_to 'Edit', edit_organization_store_path(@organization, @store)
\|
= link_to 'Back', organization_stores_path(@organization)