config/routes.rb
Configstores::Application.routes.draw do
  resources :organizations do
    resources :stores do
      resources :pairs
    end
  end
  
  
  root :to => 'organizations#index'

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :name

  has_many :stores, :dependent => :destroy
  validates :name, :presence => true, :uniqueness => true
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
      format.xml { render xml: @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
      format.xml { render xml: @organization }
    end
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
      format.xml { render xml: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(params[:organization])

    respond_to do |format|
      if @organization.save
        format.html { redirect_to organizations_path, notice: 'Organization was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
        format.xml { render xml: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
        format.xml { render xml: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to organizations_path, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
        format.xml { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
        format.xml { render xml: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
      format.xml { head :no_content }
    end
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.haml
= form_for @organization do |f|
  -if @organization.errors.any?
    #error_explanation
      %h2= "#{pluralize(@organization.errors.count, "error")} prohibited this organization from being saved:"
      %ul
        - @organization.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save', class: 'btn btn-success'
    = link_to 'Back', organizations_path, class: 'btn'

app/views/organizations/edit.html.haml
%h1 Editing organization

= render 'form'

app/views/organizations/index.html.haml
%h1 Listing organizations

%table.table.table-striped
  %thead
    %th Name
    %th
  %tbody
    - @organizations.each do |organization|
      %tr
        %td= organization.name
        %td
          = link_to 'Show stores', organization_stores_path(organization), class: 'btn'
          = link_to 'Edit', edit_organization_path(organization), class: 'btn'
          = link_to 'Destroy', organization, :confirm => 'Are you sure?', :method => :delete, class: 'btn'

= link_to 'New Organization', new_organization_path, class: 'btn'

app/views/organizations/new.html.haml
%h1 New organization

= render 'form'

app/views/organizations/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @organization.name
= link_to 'Show stores', organization_stores_path(@organization)
= link_to 'Edit', edit_organization_path(@organization)
\|
= link_to 'Back', organizations_path